# -*- coding: utf-8 -*-
"""End_to_End_ML_PIPELINE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoL7yrebmZtmqFx6y6QAn47ONvko_qYX
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

df = pd.read_csv('/content/diabetes (2).csv')

df.head()

x = df.drop(columns='Outcome', axis = 1)
y = df['Outcome']

scaler = StandardScaler()
x = scaler.fit_transform(x)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=42)

print(x.shape, x_train.shape, x_test.shape)

classifier = svm.SVC(kernel='linear')

classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_train)
acc = accuracy_score(y_train, y_pred)

print(acc)

y_pred = classifier.predict(x_test)
acc = accuracy_score(y_test, y_pred)

print(acc)

"""PREDICTIVE SYSTEM

"""

input_data = (4, 110, 92, 0, 0, 37.6, 0.191, 30)
#covert in regular form
input_numpy = np.asarray(input_data)
input_reshaped = input_numpy.reshape(1, -1)
#make it predict
std = scaler.transform(input_reshaped)
prediction = classifier.predict(std)

# The prediction is a numpy array, access its first element
if prediction[0] == 1:
  print('The person is diabetic')
else:
  print('The person is not diabetic')

"""EXPORTING AS API"""

import pickle

filename = 'model.pkl'
pickle.dump(classifier, open(filename, 'wb'))

